import {
  type KeyObject,
  createPrivateKey,
  generateKeyPairSync,
} from 'node:crypto';
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/**
 * Holder key types accepted by the issuer in `cnf.jwk`:
 * Ed25519 (EdDSA, mandatory to implement) and P-256 (ES256, optional).
 */
export type HolderKeyType = 'ed25519' | 'p256';

/** The public JWK members the issuer allows for each key type — nothing else. */
export type HolderPublicJwk =
  | { kty: 'OKP'; crv: 'Ed25519'; x: string }
  | { kty: 'EC'; crv: 'P-256'; x: string; y: string };

export interface HolderKey {
  type: HolderKeyType;
  privateKey: KeyObject;
  publicJwk: HolderPublicJwk;
  /** True when the key was generated by this call rather than read from disk. */
  created: boolean;
}

interface StoredHolderKey {
  type: HolderKeyType;
  private_jwk: Record<string, unknown>;
}

function toPublicJwk(privateKey: KeyObject): HolderPublicJwk {
  const jwk = privateKey.export({ format: 'jwk' }) as Record<string, string>;

  // Strip everything but the members the issuer allows — notably `d`, the
  // private scalar, which must never leave the local key file.
  if (jwk.kty === 'OKP') {
    return { kty: 'OKP', crv: 'Ed25519', x: jwk.x };
  }
  return { kty: 'EC', crv: 'P-256', x: jwk.x, y: jwk.y };
}

function generateHolderKey(type: HolderKeyType): KeyObject {
  if (type === 'ed25519') {
    return generateKeyPairSync('ed25519').privateKey;
  }
  return generateKeyPairSync('ec', { namedCurve: 'prime256v1' }).privateKey;
}

/**
 * Loads the holder key from `path`, generating and persisting one if the file
 * does not exist yet. The credential is bound to this key, so it must be
 * reusable across runs to be presentable later: the file is written with 0600
 * permissions and holds the private JWK.
 */
export function loadOrCreateHolderKey(
  path: string,
  type: HolderKeyType,
): HolderKey {
  let stored: StoredHolderKey | undefined;
  try {
    stored = JSON.parse(readFileSync(path, 'utf8')) as StoredHolderKey;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw new Error(
        `Failed to read holder key at ${path}: ${(error as Error).message}`,
      );
    }
  }

  if (stored) {
    const privateKey = createPrivateKey({
      key: stored.private_jwk as never,
      format: 'jwk',
    });
    return {
      type: stored.type,
      privateKey,
      publicJwk: toPublicJwk(privateKey),
      created: false,
    };
  }

  const privateKey = generateHolderKey(type);
  const payload: StoredHolderKey = {
    type,
    private_jwk: privateKey.export({ format: 'jwk' }) as Record<
      string,
      unknown
    >,
  };

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(payload, null, 2)}\n`, { mode: 0o600 });
  // writeFileSync's mode is ignored when the file already exists, so set it
  // explicitly — this file holds a private key.
  chmodSync(path, 0o600);

  return {
    type,
    privateKey,
    publicJwk: toPublicJwk(privateKey),
    created: true,
  };
}
